return {
  -- { -- Highlight, edit, and navigate code
  --   'nvim-treesitter/nvim-treesitter',
  --   build = ':TSUpdate',
  --   event = {
  --     'BufReadPost',
  --     'BufNewFile',
  --     'BufWritePre',
  --   },
  --   main = 'nvim-treesitter.configs', -- Sets main module to use for opts
  --   -- [[ Configure Treesitter ]] See `:help nvim-treesitter`
  --   opts = {
  --     ensure_installed = { 'bash', 'c', 'diff', 'html', 'hyprlang', 'lua', 'luadoc', 'markdown', 'markdown_inline', 'query', 'vim', 'vimdoc' },
  --     -- Autoinstall languages that are not installed
  --     auto_install = true,
  --     highlight = {
  --       enable = true,
  --       disable = function()
  --         -- check if 'filetype' option includes 'chezmoitmpl'
  --         if string.find(vim.bo.filetype, 'chezmoitmpl') then
  --           return true
  --         end
  --       end,
  --       -- Some languages depend on vim's regex highlighting system (such as Ruby) for indent rules.
  --       --  If you are experiencing weird indenting issues, add the language to
  --       --  the list of additional_vim_regex_highlighting and disabled languages for indent.
  --       additional_vim_regex_highlighting = { 'ruby' },
  --     },
  --     indent = { enable = true, disable = { 'ruby' } },
  --   },
  --   -- There are additional nvim-treesitter modules that you can use to interact
  --   -- with nvim-treesitter. You should go explore a few and see what interests you:
  --   --
  --   --    - Incremental selection: Included, see `:help nvim-treesitter-incremental-selection-mod`
  --   --    - Show your current context: https://github.com/nvim-treesitter/nvim-treesitter-context
  --   --    - Treesitter + textobjects: https://github.com/nvim-treesitter/nvim-treesitter-textobjects
  --   --
  --   -- config = function(_, opts)
  --   --   require('nvim-treesitter.configs').setup(opts)
  --   --   vim.filetype.add {
  --   --     pattern = { ['.*/hypr/.*%.conf'] = 'hyprlang' },
  --   --   }
  --   -- end,
  -- },
}
-- vim: ts=2 sts=2 sw=2 et
